// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/client.proto

package pb_client_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TopPageRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopPageRequest) Reset()         { *m = TopPageRequest{} }
func (m *TopPageRequest) String() string { return proto.CompactTextString(m) }
func (*TopPageRequest) ProtoMessage()    {}
func (*TopPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c344e82858e7e304, []int{0}
}

func (m *TopPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopPageRequest.Unmarshal(m, b)
}
func (m *TopPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopPageRequest.Marshal(b, m, deterministic)
}
func (m *TopPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopPageRequest.Merge(m, src)
}
func (m *TopPageRequest) XXX_Size() int {
	return xxx_messageInfo_TopPageRequest.Size(m)
}
func (m *TopPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopPageRequest proto.InternalMessageInfo

type TopPageResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopPageResponse) Reset()         { *m = TopPageResponse{} }
func (m *TopPageResponse) String() string { return proto.CompactTextString(m) }
func (*TopPageResponse) ProtoMessage()    {}
func (*TopPageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c344e82858e7e304, []int{1}
}

func (m *TopPageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopPageResponse.Unmarshal(m, b)
}
func (m *TopPageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopPageResponse.Marshal(b, m, deterministic)
}
func (m *TopPageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopPageResponse.Merge(m, src)
}
func (m *TopPageResponse) XXX_Size() int {
	return xxx_messageInfo_TopPageResponse.Size(m)
}
func (m *TopPageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TopPageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TopPageResponse proto.InternalMessageInfo

func (m *TopPageResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CallbackRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackRequest) Reset()         { *m = CallbackRequest{} }
func (m *CallbackRequest) String() string { return proto.CompactTextString(m) }
func (*CallbackRequest) ProtoMessage()    {}
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c344e82858e7e304, []int{2}
}

func (m *CallbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackRequest.Unmarshal(m, b)
}
func (m *CallbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackRequest.Marshal(b, m, deterministic)
}
func (m *CallbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackRequest.Merge(m, src)
}
func (m *CallbackRequest) XXX_Size() int {
	return xxx_messageInfo_CallbackRequest.Size(m)
}
func (m *CallbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackRequest proto.InternalMessageInfo

func (m *CallbackRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type CallbackResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackResponse) Reset()         { *m = CallbackResponse{} }
func (m *CallbackResponse) String() string { return proto.CompactTextString(m) }
func (*CallbackResponse) ProtoMessage()    {}
func (*CallbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c344e82858e7e304, []int{3}
}

func (m *CallbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackResponse.Unmarshal(m, b)
}
func (m *CallbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackResponse.Marshal(b, m, deterministic)
}
func (m *CallbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackResponse.Merge(m, src)
}
func (m *CallbackResponse) XXX_Size() int {
	return xxx_messageInfo_CallbackResponse.Size(m)
}
func (m *CallbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackResponse proto.InternalMessageInfo

func (m *CallbackResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*TopPageRequest)(nil), "pb.client.v1.TopPageRequest")
	proto.RegisterType((*TopPageResponse)(nil), "pb.client.v1.TopPageResponse")
	proto.RegisterType((*CallbackRequest)(nil), "pb.client.v1.CallbackRequest")
	proto.RegisterType((*CallbackResponse)(nil), "pb.client.v1.CallbackResponse")
}

func init() { proto.RegisterFile("pb/client.proto", fileDescriptor_c344e82858e7e304) }

var fileDescriptor_c344e82858e7e304 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x48, 0xd2, 0x4f,
	0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x29, 0x48, 0xd2,
	0x83, 0x0a, 0x94, 0x19, 0x4a, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27, 0x16, 0x64,
	0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0xd4, 0x2a, 0x09,
	0x70, 0xf1, 0x85, 0xe4, 0x17, 0x04, 0x24, 0xa6, 0xa7, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97,
	0x28, 0x29, 0x73, 0xf1, 0xc3, 0x45, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x04, 0xb8, 0x98,
	0x4b, 0x8b, 0x72, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x25, 0x55, 0x2e, 0x7e,
	0xe7, 0xc4, 0x9c, 0x9c, 0xa4, 0xc4, 0xe4, 0x6c, 0xa8, 0x3e, 0x21, 0x21, 0x2e, 0x96, 0xe4, 0xfc,
	0x94, 0x54, 0xa8, 0x2a, 0x30, 0x5b, 0x49, 0x85, 0x4b, 0x00, 0xa1, 0x0c, 0x97, 0x61, 0x46, 0x47,
	0x18, 0xb9, 0xd8, 0x9c, 0xc1, 0xee, 0x15, 0x8a, 0xe0, 0x62, 0x87, 0x5a, 0x2e, 0x24, 0xa3, 0x87,
	0xec, 0x0d, 0x3d, 0x54, 0x57, 0x4a, 0xc9, 0xe2, 0x90, 0x85, 0x58, 0xa2, 0x24, 0xd0, 0x74, 0xf9,
	0xc9, 0x64, 0x26, 0x2e, 0x21, 0x0e, 0xfd, 0x32, 0x43, 0xfd, 0x92, 0xfc, 0x02, 0x7d, 0xa1, 0x04,
	0x2e, 0x0e, 0x98, 0x53, 0x84, 0xd0, 0x34, 0xa3, 0xf9, 0x44, 0x4a, 0x0e, 0x97, 0x34, 0xd4, 0x70,
	0x51, 0xb0, 0xe1, 0xfc, 0x42, 0xbc, 0x20, 0xc3, 0x93, 0xa1, 0xb2, 0xfa, 0x49, 0x6c, 0xe0, 0x10,
	0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x08, 0x30, 0x7a, 0xf2, 0x90, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientClient is the client API for Client service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientClient interface {
	TopPage(ctx context.Context, in *TopPageRequest, opts ...grpc.CallOption) (*TopPageResponse, error)
	Callback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error)
}

type clientClient struct {
	cc *grpc.ClientConn
}

func NewClientClient(cc *grpc.ClientConn) ClientClient {
	return &clientClient{cc}
}

func (c *clientClient) TopPage(ctx context.Context, in *TopPageRequest, opts ...grpc.CallOption) (*TopPageResponse, error) {
	out := new(TopPageResponse)
	err := c.cc.Invoke(ctx, "/pb.client.v1.Client/TopPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Callback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error) {
	out := new(CallbackResponse)
	err := c.cc.Invoke(ctx, "/pb.client.v1.Client/Callback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServer is the server API for Client service.
type ClientServer interface {
	TopPage(context.Context, *TopPageRequest) (*TopPageResponse, error)
	Callback(context.Context, *CallbackRequest) (*CallbackResponse, error)
}

// UnimplementedClientServer can be embedded to have forward compatible implementations.
type UnimplementedClientServer struct {
}

func (*UnimplementedClientServer) TopPage(ctx context.Context, req *TopPageRequest) (*TopPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopPage not implemented")
}
func (*UnimplementedClientServer) Callback(ctx context.Context, req *CallbackRequest) (*CallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Callback not implemented")
}

func RegisterClientServer(s *grpc.Server, srv ClientServer) {
	s.RegisterService(&_Client_serviceDesc, srv)
}

func _Client_TopPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).TopPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.client.v1.Client/TopPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).TopPage(ctx, req.(*TopPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_Callback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).Callback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.client.v1.Client/Callback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).Callback(ctx, req.(*CallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Client_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.client.v1.Client",
	HandlerType: (*ClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TopPage",
			Handler:    _Client_TopPage_Handler,
		},
		{
			MethodName: "Callback",
			Handler:    _Client_Callback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/client.proto",
}
