// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/client.proto

package pb_client_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TopPageRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopPageRequest) Reset()         { *m = TopPageRequest{} }
func (m *TopPageRequest) String() string { return proto.CompactTextString(m) }
func (*TopPageRequest) ProtoMessage()    {}
func (*TopPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_58f00f028368c8c9, []int{0}
}
func (m *TopPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopPageRequest.Unmarshal(m, b)
}
func (m *TopPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopPageRequest.Marshal(b, m, deterministic)
}
func (dst *TopPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopPageRequest.Merge(dst, src)
}
func (m *TopPageRequest) XXX_Size() int {
	return xxx_messageInfo_TopPageRequest.Size(m)
}
func (m *TopPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopPageRequest proto.InternalMessageInfo

type TopPageResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopPageResponse) Reset()         { *m = TopPageResponse{} }
func (m *TopPageResponse) String() string { return proto.CompactTextString(m) }
func (*TopPageResponse) ProtoMessage()    {}
func (*TopPageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_58f00f028368c8c9, []int{1}
}
func (m *TopPageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopPageResponse.Unmarshal(m, b)
}
func (m *TopPageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopPageResponse.Marshal(b, m, deterministic)
}
func (dst *TopPageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopPageResponse.Merge(dst, src)
}
func (m *TopPageResponse) XXX_Size() int {
	return xxx_messageInfo_TopPageResponse.Size(m)
}
func (m *TopPageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TopPageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TopPageResponse proto.InternalMessageInfo

func (m *TopPageResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CallbackRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackRequest) Reset()         { *m = CallbackRequest{} }
func (m *CallbackRequest) String() string { return proto.CompactTextString(m) }
func (*CallbackRequest) ProtoMessage()    {}
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_58f00f028368c8c9, []int{2}
}
func (m *CallbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackRequest.Unmarshal(m, b)
}
func (m *CallbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackRequest.Marshal(b, m, deterministic)
}
func (dst *CallbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackRequest.Merge(dst, src)
}
func (m *CallbackRequest) XXX_Size() int {
	return xxx_messageInfo_CallbackRequest.Size(m)
}
func (m *CallbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackRequest proto.InternalMessageInfo

func (m *CallbackRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CallbackRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CallbackRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CallbackResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackResponse) Reset()         { *m = CallbackResponse{} }
func (m *CallbackResponse) String() string { return proto.CompactTextString(m) }
func (*CallbackResponse) ProtoMessage()    {}
func (*CallbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_58f00f028368c8c9, []int{3}
}
func (m *CallbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackResponse.Unmarshal(m, b)
}
func (m *CallbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackResponse.Marshal(b, m, deterministic)
}
func (dst *CallbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackResponse.Merge(dst, src)
}
func (m *CallbackResponse) XXX_Size() int {
	return xxx_messageInfo_CallbackResponse.Size(m)
}
func (m *CallbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackResponse proto.InternalMessageInfo

func (m *CallbackResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CallbackResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ResourceRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceRequest) Reset()         { *m = ResourceRequest{} }
func (m *ResourceRequest) String() string { return proto.CompactTextString(m) }
func (*ResourceRequest) ProtoMessage()    {}
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_58f00f028368c8c9, []int{4}
}
func (m *ResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceRequest.Unmarshal(m, b)
}
func (m *ResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceRequest.Marshal(b, m, deterministic)
}
func (dst *ResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceRequest.Merge(dst, src)
}
func (m *ResourceRequest) XXX_Size() int {
	return xxx_messageInfo_ResourceRequest.Size(m)
}
func (m *ResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceRequest proto.InternalMessageInfo

func (m *ResourceRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ResourceResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceResponse) Reset()         { *m = ResourceResponse{} }
func (m *ResourceResponse) String() string { return proto.CompactTextString(m) }
func (*ResourceResponse) ProtoMessage()    {}
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_58f00f028368c8c9, []int{5}
}
func (m *ResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceResponse.Unmarshal(m, b)
}
func (m *ResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceResponse.Marshal(b, m, deterministic)
}
func (dst *ResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceResponse.Merge(dst, src)
}
func (m *ResourceResponse) XXX_Size() int {
	return xxx_messageInfo_ResourceResponse.Size(m)
}
func (m *ResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceResponse proto.InternalMessageInfo

func (m *ResourceResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResourceResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*TopPageRequest)(nil), "pb.client.v1.TopPageRequest")
	proto.RegisterType((*TopPageResponse)(nil), "pb.client.v1.TopPageResponse")
	proto.RegisterType((*CallbackRequest)(nil), "pb.client.v1.CallbackRequest")
	proto.RegisterType((*CallbackResponse)(nil), "pb.client.v1.CallbackResponse")
	proto.RegisterType((*ResourceRequest)(nil), "pb.client.v1.ResourceRequest")
	proto.RegisterType((*ResourceResponse)(nil), "pb.client.v1.ResourceResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientClient is the client API for Client service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientClient interface {
	TopPage(ctx context.Context, in *TopPageRequest, opts ...grpc.CallOption) (*TopPageResponse, error)
	Callback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error)
	Resource(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error)
}

type clientClient struct {
	cc *grpc.ClientConn
}

func NewClientClient(cc *grpc.ClientConn) ClientClient {
	return &clientClient{cc}
}

func (c *clientClient) TopPage(ctx context.Context, in *TopPageRequest, opts ...grpc.CallOption) (*TopPageResponse, error) {
	out := new(TopPageResponse)
	err := c.cc.Invoke(ctx, "/pb.client.v1.Client/TopPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Callback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error) {
	out := new(CallbackResponse)
	err := c.cc.Invoke(ctx, "/pb.client.v1.Client/Callback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Resource(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error) {
	out := new(ResourceResponse)
	err := c.cc.Invoke(ctx, "/pb.client.v1.Client/Resource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServer is the server API for Client service.
type ClientServer interface {
	TopPage(context.Context, *TopPageRequest) (*TopPageResponse, error)
	Callback(context.Context, *CallbackRequest) (*CallbackResponse, error)
	Resource(context.Context, *ResourceRequest) (*ResourceResponse, error)
}

func RegisterClientServer(s *grpc.Server, srv ClientServer) {
	s.RegisterService(&_Client_serviceDesc, srv)
}

func _Client_TopPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).TopPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.client.v1.Client/TopPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).TopPage(ctx, req.(*TopPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_Callback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).Callback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.client.v1.Client/Callback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).Callback(ctx, req.(*CallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_Resource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).Resource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.client.v1.Client/Resource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).Resource(ctx, req.(*ResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Client_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.client.v1.Client",
	HandlerType: (*ClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TopPage",
			Handler:    _Client_TopPage_Handler,
		},
		{
			MethodName: "Callback",
			Handler:    _Client_Callback_Handler,
		},
		{
			MethodName: "Resource",
			Handler:    _Client_Resource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/client.proto",
}

func init() { proto.RegisterFile("pb/client.proto", fileDescriptor_client_58f00f028368c8c9) }

var fileDescriptor_client_58f00f028368c8c9 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4d, 0x6a, 0xfb, 0x30,
	0x10, 0xc5, 0x89, 0x93, 0x7f, 0x3e, 0x86, 0x10, 0x9b, 0x21, 0xfc, 0x6b, 0x42, 0x1a, 0x8a, 0xbb,
	0x29, 0x5d, 0xd8, 0xa4, 0xdd, 0xb6, 0xab, 0xac, 0xba, 0x2b, 0x21, 0xd0, 0x65, 0x90, 0x1d, 0x11,
	0x4c, 0x1d, 0x49, 0xb5, 0xe4, 0x6c, 0x4a, 0x37, 0xbd, 0x42, 0xcf, 0xd1, 0xd3, 0xf4, 0x0a, 0x3d,
	0x48, 0x91, 0x22, 0xe7, 0x43, 0x90, 0x9d, 0x66, 0xe6, 0xcd, 0x7b, 0xcc, 0x0f, 0x81, 0x2f, 0xd2,
	0x24, 0x2b, 0x72, 0xca, 0x54, 0x2c, 0x4a, 0xae, 0x38, 0xf6, 0x45, 0x1a, 0xdb, 0xc6, 0x76, 0x3a,
	0x1a, 0xaf, 0x39, 0x5f, 0x17, 0x34, 0x21, 0x22, 0x4f, 0x08, 0x63, 0x5c, 0x11, 0x95, 0x73, 0x26,
	0x77, 0xda, 0x28, 0x80, 0xc1, 0x82, 0x8b, 0x67, 0xb2, 0xa6, 0x73, 0xfa, 0x56, 0x51, 0xa9, 0xa2,
	0x6b, 0xf0, 0xf7, 0x1d, 0x29, 0x38, 0x93, 0x14, 0x03, 0x68, 0x56, 0x65, 0x11, 0x36, 0xae, 0x1a,
	0x37, 0xbd, 0xb9, 0x7e, 0x46, 0x0b, 0xf0, 0x67, 0xa4, 0x28, 0x52, 0x92, 0xbd, 0xda, 0x3d, 0x44,
	0x68, 0x65, 0x7c, 0x45, 0xad, 0xca, 0xbc, 0x71, 0x08, 0xff, 0xa4, 0x22, 0x8a, 0x86, 0x9e, 0x69,
	0xee, 0x0a, 0xbc, 0x80, 0x4e, 0x25, 0x69, 0xb9, 0xcc, 0x57, 0x61, 0xd3, 0xf4, 0xdb, 0xba, 0x7c,
	0x5a, 0x45, 0x8f, 0x10, 0x1c, 0x5c, 0xcf, 0x65, 0x1f, 0xaf, 0x7b, 0x27, 0xeb, 0xb7, 0xe0, 0xcf,
	0xa9, 0xe4, 0x55, 0x99, 0xd5, 0xc7, 0x1c, 0x6b, 0x1b, 0x27, 0xda, 0x07, 0x08, 0x0e, 0x5a, 0x1b,
	0x85, 0xd0, 0x62, 0x64, 0xb3, 0xbf, 0x40, 0xbf, 0xf5, 0x05, 0x74, 0x43, 0xf2, 0xa2, 0xbe, 0xc0,
	0x14, 0x77, 0xdf, 0x1e, 0xb4, 0x67, 0x86, 0x30, 0xbe, 0x40, 0xc7, 0xe2, 0xc2, 0x71, 0x7c, 0x0c,
	0x3e, 0x3e, 0xe5, 0x3a, 0xba, 0x3c, 0x33, 0xdd, 0x85, 0x47, 0xfe, 0xe7, 0xcf, 0xef, 0x97, 0xd7,
	0xc3, 0x4e, 0xb2, 0x9d, 0x26, 0x8a, 0x0b, 0x5c, 0x42, 0xb7, 0x86, 0x81, 0xce, 0xae, 0x83, 0x7e,
	0x34, 0x39, 0x37, 0xb6, 0xde, 0x43, 0xe3, 0x3d, 0xc0, 0xbe, 0xf6, 0xce, 0x6a, 0xd3, 0x1c, 0xba,
	0x35, 0x02, 0x37, 0xc0, 0xc1, 0xe8, 0x06, 0xb8, 0xe4, 0xa2, 0x89, 0x09, 0x08, 0xf1, 0xbf, 0x0e,
	0x28, 0xed, 0x34, 0x79, 0xb7, 0xe8, 0x3f, 0xd2, 0xb6, 0xf9, 0x6c, 0xf7, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x36, 0x73, 0x63, 0xdb, 0xab, 0x02, 0x00, 0x00,
}
