// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/auth.proto

package pb_auth_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthorizationRequest struct {
	ResponseType                          string   `protobuf:"bytes,1,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	Scope                                 string   `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	ClientId                              string   `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RedirectUri                           string   `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	State                                 string   `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	TlsClientCertificateBoundAccessTokens bool     `protobuf:"varint,6,opt,name=tls_client_certificate_bound_access_tokens,json=tlsClientCertificateBoundAccessTokens,proto3" json:"tls_client_certificate_bound_access_tokens,omitempty"`
	XXX_NoUnkeyedLiteral                  struct{} `json:"-"`
	XXX_unrecognized                      []byte   `json:"-"`
	XXX_sizecache                         int32    `json:"-"`
}

func (m *AuthorizationRequest) Reset()         { *m = AuthorizationRequest{} }
func (m *AuthorizationRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorizationRequest) ProtoMessage()    {}
func (*AuthorizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43ab4a3390919ea, []int{0}
}

func (m *AuthorizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationRequest.Unmarshal(m, b)
}
func (m *AuthorizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationRequest.Marshal(b, m, deterministic)
}
func (m *AuthorizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationRequest.Merge(m, src)
}
func (m *AuthorizationRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorizationRequest.Size(m)
}
func (m *AuthorizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationRequest proto.InternalMessageInfo

func (m *AuthorizationRequest) GetResponseType() string {
	if m != nil {
		return m.ResponseType
	}
	return ""
}

func (m *AuthorizationRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *AuthorizationRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *AuthorizationRequest) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

func (m *AuthorizationRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AuthorizationRequest) GetTlsClientCertificateBoundAccessTokens() bool {
	if m != nil {
		return m.TlsClientCertificateBoundAccessTokens
	}
	return false
}

type AuthorizationResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RedirectUri          string   `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationResponse) Reset()         { *m = AuthorizationResponse{} }
func (m *AuthorizationResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorizationResponse) ProtoMessage()    {}
func (*AuthorizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43ab4a3390919ea, []int{1}
}

func (m *AuthorizationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationResponse.Unmarshal(m, b)
}
func (m *AuthorizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationResponse.Marshal(b, m, deterministic)
}
func (m *AuthorizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationResponse.Merge(m, src)
}
func (m *AuthorizationResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorizationResponse.Size(m)
}
func (m *AuthorizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationResponse proto.InternalMessageInfo

func (m *AuthorizationResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AuthorizationResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AuthorizationResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthorizationResponse) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

type IssueTokenRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	GrantType            string   `protobuf:"bytes,2,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	RedirectUri          string   `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueTokenRequest) Reset()         { *m = IssueTokenRequest{} }
func (m *IssueTokenRequest) String() string { return proto.CompactTextString(m) }
func (*IssueTokenRequest) ProtoMessage()    {}
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43ab4a3390919ea, []int{2}
}

func (m *IssueTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueTokenRequest.Unmarshal(m, b)
}
func (m *IssueTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueTokenRequest.Marshal(b, m, deterministic)
}
func (m *IssueTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueTokenRequest.Merge(m, src)
}
func (m *IssueTokenRequest) XXX_Size() int {
	return xxx_messageInfo_IssueTokenRequest.Size(m)
}
func (m *IssueTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IssueTokenRequest proto.InternalMessageInfo

func (m *IssueTokenRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *IssueTokenRequest) GetGrantType() string {
	if m != nil {
		return m.GrantType
	}
	return ""
}

func (m *IssueTokenRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *IssueTokenRequest) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

type IssueTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueTokenResponse) Reset()         { *m = IssueTokenResponse{} }
func (m *IssueTokenResponse) String() string { return proto.CompactTextString(m) }
func (*IssueTokenResponse) ProtoMessage()    {}
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43ab4a3390919ea, []int{3}
}

func (m *IssueTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueTokenResponse.Unmarshal(m, b)
}
func (m *IssueTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueTokenResponse.Marshal(b, m, deterministic)
}
func (m *IssueTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueTokenResponse.Merge(m, src)
}
func (m *IssueTokenResponse) XXX_Size() int {
	return xxx_messageInfo_IssueTokenResponse.Size(m)
}
func (m *IssueTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IssueTokenResponse proto.InternalMessageInfo

func (m *IssueTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyTokenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenRequest) Reset()         { *m = VerifyTokenRequest{} }
func (m *VerifyTokenRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenRequest) ProtoMessage()    {}
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43ab4a3390919ea, []int{4}
}

func (m *VerifyTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenRequest.Unmarshal(m, b)
}
func (m *VerifyTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenRequest.Marshal(b, m, deterministic)
}
func (m *VerifyTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenRequest.Merge(m, src)
}
func (m *VerifyTokenRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenRequest.Size(m)
}
func (m *VerifyTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenRequest proto.InternalMessageInfo

type VerifyTokenResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenResponse) Reset()         { *m = VerifyTokenResponse{} }
func (m *VerifyTokenResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenResponse) ProtoMessage()    {}
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43ab4a3390919ea, []int{5}
}

func (m *VerifyTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenResponse.Unmarshal(m, b)
}
func (m *VerifyTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenResponse.Marshal(b, m, deterministic)
}
func (m *VerifyTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenResponse.Merge(m, src)
}
func (m *VerifyTokenResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenResponse.Size(m)
}
func (m *VerifyTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenResponse proto.InternalMessageInfo

func (m *VerifyTokenResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type IntrospectiveRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntrospectiveRequest) Reset()         { *m = IntrospectiveRequest{} }
func (m *IntrospectiveRequest) String() string { return proto.CompactTextString(m) }
func (*IntrospectiveRequest) ProtoMessage()    {}
func (*IntrospectiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43ab4a3390919ea, []int{6}
}

func (m *IntrospectiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntrospectiveRequest.Unmarshal(m, b)
}
func (m *IntrospectiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntrospectiveRequest.Marshal(b, m, deterministic)
}
func (m *IntrospectiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntrospectiveRequest.Merge(m, src)
}
func (m *IntrospectiveRequest) XXX_Size() int {
	return xxx_messageInfo_IntrospectiveRequest.Size(m)
}
func (m *IntrospectiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IntrospectiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IntrospectiveRequest proto.InternalMessageInfo

func (m *IntrospectiveRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type IntrospectiveResponse struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	DnsName              string   `protobuf:"bytes,3,opt,name=dns_name,json=dnsName,proto3" json:"dns_name,omitempty"`
	X5T                  string   `protobuf:"bytes,4,opt,name=x5t,proto3" json:"x5t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntrospectiveResponse) Reset()         { *m = IntrospectiveResponse{} }
func (m *IntrospectiveResponse) String() string { return proto.CompactTextString(m) }
func (*IntrospectiveResponse) ProtoMessage()    {}
func (*IntrospectiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43ab4a3390919ea, []int{7}
}

func (m *IntrospectiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntrospectiveResponse.Unmarshal(m, b)
}
func (m *IntrospectiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntrospectiveResponse.Marshal(b, m, deterministic)
}
func (m *IntrospectiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntrospectiveResponse.Merge(m, src)
}
func (m *IntrospectiveResponse) XXX_Size() int {
	return xxx_messageInfo_IntrospectiveResponse.Size(m)
}
func (m *IntrospectiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IntrospectiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IntrospectiveResponse proto.InternalMessageInfo

func (m *IntrospectiveResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *IntrospectiveResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *IntrospectiveResponse) GetDnsName() string {
	if m != nil {
		return m.DnsName
	}
	return ""
}

func (m *IntrospectiveResponse) GetX5T() string {
	if m != nil {
		return m.X5T
	}
	return ""
}

type RegistRequest struct {
	Name                                  string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TlsClientAuthSanDns                   string   `protobuf:"bytes,2,opt,name=tls_client_auth_san_dns,json=tlsClientAuthSanDns,proto3" json:"tls_client_auth_san_dns,omitempty"`
	TlsClientCertificateBoundAccessTokens bool     `protobuf:"varint,3,opt,name=tls_client_certificate_bound_access_tokens,json=tlsClientCertificateBoundAccessTokens,proto3" json:"tls_client_certificate_bound_access_tokens,omitempty"`
	XXX_NoUnkeyedLiteral                  struct{} `json:"-"`
	XXX_unrecognized                      []byte   `json:"-"`
	XXX_sizecache                         int32    `json:"-"`
}

func (m *RegistRequest) Reset()         { *m = RegistRequest{} }
func (m *RegistRequest) String() string { return proto.CompactTextString(m) }
func (*RegistRequest) ProtoMessage()    {}
func (*RegistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43ab4a3390919ea, []int{8}
}

func (m *RegistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistRequest.Unmarshal(m, b)
}
func (m *RegistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistRequest.Marshal(b, m, deterministic)
}
func (m *RegistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistRequest.Merge(m, src)
}
func (m *RegistRequest) XXX_Size() int {
	return xxx_messageInfo_RegistRequest.Size(m)
}
func (m *RegistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistRequest proto.InternalMessageInfo

func (m *RegistRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegistRequest) GetTlsClientAuthSanDns() string {
	if m != nil {
		return m.TlsClientAuthSanDns
	}
	return ""
}

func (m *RegistRequest) GetTlsClientCertificateBoundAccessTokens() bool {
	if m != nil {
		return m.TlsClientCertificateBoundAccessTokens
	}
	return false
}

type RegistResponse struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TlsClientAuthSanDns  string   `protobuf:"bytes,3,opt,name=tls_client_auth_san_dns,json=tlsClientAuthSanDns,proto3" json:"tls_client_auth_san_dns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistResponse) Reset()         { *m = RegistResponse{} }
func (m *RegistResponse) String() string { return proto.CompactTextString(m) }
func (*RegistResponse) ProtoMessage()    {}
func (*RegistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43ab4a3390919ea, []int{9}
}

func (m *RegistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistResponse.Unmarshal(m, b)
}
func (m *RegistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistResponse.Marshal(b, m, deterministic)
}
func (m *RegistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistResponse.Merge(m, src)
}
func (m *RegistResponse) XXX_Size() int {
	return xxx_messageInfo_RegistResponse.Size(m)
}
func (m *RegistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistResponse proto.InternalMessageInfo

func (m *RegistResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *RegistResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegistResponse) GetTlsClientAuthSanDns() string {
	if m != nil {
		return m.TlsClientAuthSanDns
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthorizationRequest)(nil), "pb.auth.v1.AuthorizationRequest")
	proto.RegisterType((*AuthorizationResponse)(nil), "pb.auth.v1.AuthorizationResponse")
	proto.RegisterType((*IssueTokenRequest)(nil), "pb.auth.v1.IssueTokenRequest")
	proto.RegisterType((*IssueTokenResponse)(nil), "pb.auth.v1.IssueTokenResponse")
	proto.RegisterType((*VerifyTokenRequest)(nil), "pb.auth.v1.VerifyTokenRequest")
	proto.RegisterType((*VerifyTokenResponse)(nil), "pb.auth.v1.VerifyTokenResponse")
	proto.RegisterType((*IntrospectiveRequest)(nil), "pb.auth.v1.IntrospectiveRequest")
	proto.RegisterType((*IntrospectiveResponse)(nil), "pb.auth.v1.IntrospectiveResponse")
	proto.RegisterType((*RegistRequest)(nil), "pb.auth.v1.RegistRequest")
	proto.RegisterType((*RegistResponse)(nil), "pb.auth.v1.RegistResponse")
}

func init() { proto.RegisterFile("pb/auth.proto", fileDescriptor_c43ab4a3390919ea) }

var fileDescriptor_c43ab4a3390919ea = []byte{
	// 634 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x4e, 0xd4, 0x40,
	0x14, 0x66, 0xdb, 0x65, 0x59, 0x0e, 0xac, 0xd1, 0x61, 0x91, 0x52, 0x44, 0xa1, 0xc6, 0x84, 0x10,
	0x5d, 0xe2, 0xdf, 0x03, 0x20, 0xde, 0x70, 0xa1, 0x31, 0x2b, 0x92, 0x78, 0xd5, 0xcc, 0xb6, 0x87,
	0x65, 0xe2, 0x32, 0x53, 0x66, 0xa6, 0xe8, 0x9a, 0x78, 0xc3, 0x85, 0x2f, 0xe0, 0xab, 0xe8, 0x93,
	0xf8, 0x0a, 0x3e, 0x88, 0xe9, 0xb4, 0x43, 0xdb, 0x65, 0x21, 0x70, 0xd3, 0xcc, 0xf9, 0x99, 0x33,
	0xdf, 0xf9, 0xe6, 0x3b, 0x53, 0xe8, 0x24, 0x83, 0x1d, 0x9a, 0xea, 0xe3, 0x5e, 0x22, 0x85, 0x16,
	0x04, 0x92, 0x41, 0xcf, 0x98, 0x67, 0xcf, 0xfd, 0x07, 0x43, 0x21, 0x86, 0x23, 0xdc, 0xa1, 0x09,
	0xdb, 0xa1, 0x9c, 0x0b, 0x4d, 0x35, 0x13, 0x5c, 0xe5, 0x99, 0xc1, 0xb9, 0x03, 0xdd, 0xdd, 0x54,
	0x1f, 0x0b, 0xc9, 0xbe, 0x9b, 0x40, 0x1f, 0x4f, 0x53, 0x54, 0x9a, 0x3c, 0x86, 0x8e, 0x44, 0x95,
	0x08, 0xae, 0x30, 0xd4, 0xe3, 0x04, 0xbd, 0xc6, 0x46, 0x63, 0x6b, 0xbe, 0xbf, 0x68, 0x9d, 0x07,
	0xe3, 0x04, 0x49, 0x17, 0x66, 0x55, 0x24, 0x12, 0xf4, 0x1c, 0x13, 0xcc, 0x0d, 0xb2, 0x06, 0xf3,
	0xd1, 0x88, 0x21, 0xd7, 0x21, 0x8b, 0x3d, 0xd7, 0x44, 0xda, 0xb9, 0x63, 0x3f, 0x26, 0x9b, 0xb0,
	0x28, 0x31, 0x66, 0x12, 0x23, 0x1d, 0xa6, 0x92, 0x79, 0x4d, 0x13, 0x5f, 0xb0, 0xbe, 0x4f, 0x92,
	0x99, 0xaa, 0x9a, 0x6a, 0xf4, 0x66, 0x8b, 0xaa, 0x99, 0x41, 0x3e, 0xc3, 0xb6, 0x1e, 0xa9, 0xb0,
	0xa8, 0x1c, 0xa1, 0xd4, 0xec, 0x88, 0x45, 0x54, 0x63, 0x38, 0x10, 0x29, 0x8f, 0x43, 0x1a, 0x45,
	0xa8, 0x54, 0xa8, 0xc5, 0x17, 0xe4, 0xca, 0x6b, 0x6d, 0x34, 0xb6, 0xda, 0xfd, 0x27, 0x7a, 0xa4,
	0xf6, 0xcc, 0x86, 0xbd, 0x32, 0xff, 0x4d, 0x96, 0xbe, 0x6b, 0xb2, 0x0f, 0x4c, 0x72, 0xf0, 0x03,
	0x96, 0x27, 0x38, 0xc8, 0x7b, 0x24, 0x04, 0x9a, 0x91, 0x88, 0x6d, 0xef, 0x66, 0x5d, 0xa2, 0x73,
	0xaa, 0xe8, 0x56, 0x60, 0x2e, 0x55, 0x28, 0xcb, 0x8e, 0x5b, 0x99, 0x79, 0xa3, 0x7e, 0x83, 0x9f,
	0x0d, 0xb8, 0xb7, 0xaf, 0x54, 0x8a, 0x06, 0x8e, 0xbd, 0x80, 0x1a, 0x8b, 0x8d, 0x09, 0x16, 0xd7,
	0x01, 0x86, 0x92, 0x72, 0x9d, 0x5f, 0x4d, 0x8e, 0x64, 0xde, 0x78, 0xcc, 0xbd, 0x58, 0xdc, 0x6e,
	0x05, 0xf7, 0x0d, 0x80, 0x6c, 0x03, 0xa9, 0xe2, 0x28, 0x48, 0xe8, 0xc2, 0xac, 0x21, 0xb5, 0x00,
	0x91, 0x1b, 0x41, 0x17, 0xc8, 0x21, 0x4a, 0x76, 0x34, 0xae, 0x82, 0x0e, 0x9e, 0xc1, 0x52, 0xcd,
	0x5b, 0x94, 0xb8, 0x0f, 0x2d, 0x89, 0x2a, 0x1d, 0x69, 0x53, 0xa3, 0xdd, 0x2f, 0xac, 0xe0, 0x29,
	0x74, 0xf7, 0xb9, 0x96, 0x42, 0x25, 0x18, 0x69, 0x76, 0x86, 0xb6, 0xf7, 0xe9, 0x47, 0x8e, 0x61,
	0x79, 0x22, 0xbb, 0x2c, 0x4f, 0x8d, 0xc7, 0x96, 0xcf, 0xad, 0x3a, 0x85, 0xce, 0x04, 0x85, 0xab,
	0xd0, 0x8e, 0xb9, 0x0a, 0x39, 0x3d, 0xb1, 0x3c, 0xcd, 0xc5, 0x5c, 0xbd, 0xa7, 0x27, 0x48, 0xee,
	0x82, 0xfb, 0xed, 0xb5, 0x2e, 0x18, 0xca, 0x96, 0xc1, 0xef, 0x06, 0x74, 0xfa, 0x38, 0x64, 0x4a,
	0x5b, 0x88, 0x04, 0x9a, 0x66, 0x6b, 0x21, 0x8d, 0x6c, 0x4d, 0x5e, 0xc1, 0x4a, 0x45, 0xa2, 0xd9,
	0x00, 0x86, 0x8a, 0xf2, 0x30, 0xe6, 0xaa, 0x38, 0x7d, 0xe9, 0x42, 0x8f, 0x99, 0xde, 0x3e, 0x52,
	0xfe, 0x96, 0xab, 0x5b, 0x0a, 0xdb, 0xbd, 0x8d, 0xb0, 0xbf, 0xc2, 0x1d, 0x8b, 0xba, 0xa0, 0xea,
	0x5a, 0x55, 0xd9, 0x9e, 0x9c, 0x9b, 0xf5, 0xe4, 0x5e, 0xd9, 0xd3, 0x8b, 0x3f, 0x2e, 0x34, 0x33,
	0x93, 0x9c, 0x42, 0xa7, 0x36, 0x5a, 0x64, 0xa3, 0x57, 0xbe, 0x4d, 0xbd, 0x69, 0x2f, 0x8f, 0xbf,
	0x79, 0x4d, 0x46, 0xde, 0x45, 0xb0, 0x76, 0xfe, 0xf7, 0xdf, 0x2f, 0x67, 0x99, 0x2c, 0x99, 0x47,
	0xcf, 0x7c, 0xca, 0x13, 0xde, 0x01, 0x94, 0x2a, 0x26, 0xeb, 0xd5, 0x6a, 0x97, 0xa6, 0xcc, 0x7f,
	0x78, 0x55, 0xb8, 0x38, 0x69, 0x86, 0x7c, 0x80, 0x85, 0x8a, 0xa4, 0x49, 0x6d, 0xc3, 0xe5, 0x09,
	0xf0, 0x1f, 0x5d, 0x19, 0xbf, 0xa8, 0x78, 0x08, 0x9d, 0x9a, 0x8e, 0xeb, 0x9c, 0x4c, 0x1b, 0x88,
	0x3a, 0x27, 0x53, 0x87, 0x20, 0x98, 0x21, 0xbb, 0xd0, 0xca, 0x6f, 0x9b, 0xac, 0x56, 0xd3, 0x6b,
	0xba, 0xf5, 0xfd, 0x69, 0x21, 0x5b, 0x62, 0xd0, 0x32, 0x7f, 0x85, 0x97, 0xff, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xd2, 0xa5, 0x7b, 0xc9, 0x50, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Authorization(ctx context.Context, in *AuthorizationRequest, opts ...grpc.CallOption) (*AuthorizationResponse, error)
	IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error)
	VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
	Introspective(ctx context.Context, in *IntrospectiveRequest, opts ...grpc.CallOption) (*IntrospectiveResponse, error)
	Regist(ctx context.Context, in *RegistRequest, opts ...grpc.CallOption) (*RegistResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Authorization(ctx context.Context, in *AuthorizationRequest, opts ...grpc.CallOption) (*AuthorizationResponse, error) {
	out := new(AuthorizationResponse)
	err := c.cc.Invoke(ctx, "/pb.auth.v1.Auth/Authorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error) {
	out := new(IssueTokenResponse)
	err := c.cc.Invoke(ctx, "/pb.auth.v1.Auth/IssueToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	out := new(VerifyTokenResponse)
	err := c.cc.Invoke(ctx, "/pb.auth.v1.Auth/VerifyToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Introspective(ctx context.Context, in *IntrospectiveRequest, opts ...grpc.CallOption) (*IntrospectiveResponse, error) {
	out := new(IntrospectiveResponse)
	err := c.cc.Invoke(ctx, "/pb.auth.v1.Auth/Introspective", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Regist(ctx context.Context, in *RegistRequest, opts ...grpc.CallOption) (*RegistResponse, error) {
	out := new(RegistResponse)
	err := c.cc.Invoke(ctx, "/pb.auth.v1.Auth/Regist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Authorization(context.Context, *AuthorizationRequest) (*AuthorizationResponse, error)
	IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error)
	VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error)
	Introspective(context.Context, *IntrospectiveRequest) (*IntrospectiveResponse, error)
	Regist(context.Context, *RegistRequest) (*RegistResponse, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Authorization(ctx context.Context, req *AuthorizationRequest) (*AuthorizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorization not implemented")
}
func (*UnimplementedAuthServer) IssueToken(ctx context.Context, req *IssueTokenRequest) (*IssueTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueToken not implemented")
}
func (*UnimplementedAuthServer) VerifyToken(ctx context.Context, req *VerifyTokenRequest) (*VerifyTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (*UnimplementedAuthServer) Introspective(ctx context.Context, req *IntrospectiveRequest) (*IntrospectiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Introspective not implemented")
}
func (*UnimplementedAuthServer) Regist(ctx context.Context, req *RegistRequest) (*RegistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Regist not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Authorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Authorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.auth.v1.Auth/Authorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Authorization(ctx, req.(*AuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.auth.v1.Auth/IssueToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).IssueToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.auth.v1.Auth/VerifyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).VerifyToken(ctx, req.(*VerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Introspective_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntrospectiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Introspective(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.auth.v1.Auth/Introspective",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Introspective(ctx, req.(*IntrospectiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Regist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Regist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.auth.v1.Auth/Regist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Regist(ctx, req.(*RegistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.auth.v1.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorization",
			Handler:    _Auth_Authorization_Handler,
		},
		{
			MethodName: "IssueToken",
			Handler:    _Auth_IssueToken_Handler,
		},
		{
			MethodName: "VerifyToken",
			Handler:    _Auth_VerifyToken_Handler,
		},
		{
			MethodName: "Introspective",
			Handler:    _Auth_Introspective_Handler,
		},
		{
			MethodName: "Regist",
			Handler:    _Auth_Regist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/auth.proto",
}
